### ISSUE TITLE
sc2::Unit::tag truncation

### ISSUE THREAD

**Issue by KevinCalderone** [davechurchill/commandcenter#16]
In "UnitData.cpp" you are casting "sc2::Unit::tag" to an int when you operate with it. This value is a 64-bit integer, and we DO use the bits in the upper word. By truncating it to a 32-bit integer you may be introducing tag collisions.

I suggest you use the same 64-bit integer type the api library does:
typedef uint64_t Tag;

**Comment by davechurchill** [comment]
Fixed, thanks!
