### ISSUE TITLE
Cmdline parameters

### ISSUE THREAD

**Issue by alkurbatov** [davechurchill/commandcenter#20]
Current bot implementation allows to pass cmdline parameters to sc2api directly:
```C++
   if (!coordinator.LoadSettings(argc, argv)) 
    {
        std::cout << "Unable to find or parse settings." << std::endl;
        return 1;
    }
```

Is it intended? I can pass things like '--help', 'map_path', 'realtime' and so on while the same parameters are duplicated in BotConfig.txt and some are discarded in the code below. Looks confusing.

Probably better solution will be to limit number of parameters delivered to sc2api::Coordinator, e.g. pass only program name:
```C++
    sc2::Coordinator coordinator;
    coordinator.LoadSettings(1, argv);
```

**Comment by davechurchill** [comment]
Will look into this later, but not high priority

**Comment by davechurchill** [comment]
Decided that I won't look into this, because CC uses the config only. Any command line parameters will be undefined behaviour :D

**Comment by alkurbatov** [comment]
That must be documented otherwise it could cause confusion.
