### ISSUE TITLE
localtime_s, vsnprintf_s unsupported on g++/clang++

### ISSUE THREAD

**Issue by kuzi117** [davechurchill/commandcenter#23]
As [seen here](http://en.cppreference.com/w/c/chrono/localtime), *_s is only available if `__STDC_LIB_EXT1__` is defined by the implementation and if `__STDC_WANT_LIB_EXT1__` is defined to `1` before including ctime. These are unfortunately not available to me on g++/clang++. Is there a solution to this?

**Comment by davechurchill** [comment]
I have already begun replacing these functions :)

**Comment by kuzi117** [comment]
Alright, thanks for the quick response!

**Comment by davechurchill** [comment]
fixed
