### ISSUE TITLE
Uncaught exception, key not found.

### ISSUE THREAD

**Issue by Skarlso** [davechurchill/commandcenter#26]
Hey, so I'm running the bot. I'm using the BotConfig and all is fine. And then suddenly, BAMM.

```
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: map::at:  key not found
```

And that's that. I'm on OSX.

**Comment by davechurchill** [comment]
Can you try running the bot in debug mode and telling me the line of code that this is triggered on?

**Comment by Skarlso** [comment]
Yeah, I will. Sorry for the late answer.
