### ISSUE TITLE
Error compiling for ubuntu linux (cmake linking commandcenter).

### ISSUE THREAD

**Issue by jhor296** [davechurchill/commandcenter#41]
Hi. At the end of the compilation process with cmake fails in linking executable. A sample of the error:

.....
[ 94%] Building CXX object src/CMakeFiles/CommandCenter.dir/WorkerManager.cpp.o
/home/juanj/apps/s2client-api/commandcenter/src/WorkerManager.cpp: In member function ‘void WorkerManager::drawWorkerInformation()’:
/home/juanj/apps/s2client-api/commandcenter/src/WorkerManager.cpp:235:9: warning: unused variable ‘yspace’ [-Wunused-variable]
     int yspace = 0;
         ^~~~~~
[ 97%] Building CXX object src/CMakeFiles/CommandCenter.dir/main.cpp.o
[100%] Linking CXX executable ../bin/CommandCenter
/opt/local/lib/sc2api/libsc2api.a(sc2_agent.cc.o): On function: `google::protobuf::RepeatedField<unsigned long long>::Reserve(int)':
sc2_agent.cc:(.text._ZN6google8protobuf13RepeatedFieldIyE7ReserveEi[_ZN6google8protobuf13RepeatedFieldIyE7ReserveEi]+0xdf): reference to `google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)' not defined
sc2_agent.cc:(.text._ZN6google8protobuf13RepeatedFieldIyE7ReserveEi[_ZN6google8protobuf13RepeatedFieldIyE7ReserveEi]+0xf7): reference to `google::protobuf::internal::LogMessage::operator<<(char const*)' not defined
sc2_agent.cc:(.text._ZN6google8protobuf13RepeatedFieldIyE7ReserveEi[_ZN6google8protobuf13RepeatedFieldIyE7ReserveEi]+0x106): reference to `google::protobuf::internal::LogMessage::operator<<(char const*)' not defined
sc2_agent.cc:(.text._ZN6google8protobuf13RepeatedFieldIyE7ReserveEi[_ZN6google8protobuf13RepeatedFieldIyE7ReserveEi]+0x11b): reference to `google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&)' not defined
...............................................................................................................

Thanks.

**Comment by alkurbatov** [comment]
Hi, @jhor296 ,
please check that you use protabuf from the sc2api because it is not the same as protobuf from your repos.

Also we haven’t tested the build under static libraries so problems could be.

**Comment by jhor296** [comment]
Hello again.
I have checked my system and I don't have the protobuf-compiler package (protoc) installed (Ubuntu 17.04 64bits).
