### ISSUE TITLE
Question: Set the "Working Directory" option properly in VS2017

### ISSUE THREAD

**Issue by benjamin-ross** [davechurchill/commandcenter#44]
In your Compile Instructions, you wrote "Click "Local Windows Debugger" in VS to launch the program from within VS. To do this, you need to set the "Working Directory" option under "Debugging" to "$(ProjectDir)/../bin/" (I don't know why this option won't save)". Is it because your `/vs/CommandCenter.vcxproj.user` was not pushed due to the `.gitignore` ? Can a simple `git add CommandCenter.vcxproj.user -f` will solve this issue ?

**Comment by davechurchill** [comment]
Oooh that makes sense! I will check this out soon.
