### ISSUE TITLE
command center stoped working during initialization of units

### ISSUE THREAD

**Issue by slimak2** [davechurchill/commandcenter#45]
Hi, i am trying to make command center work on windows, but when the game starts it trows error.
Could someone help me please?

if I run CommandCenter_d.exe then

WaitJoinGame finished successfully
vc\tools\msvc\14.10.25017\include\vector
line 1754
expression: vector subscript out of range

if run CommandCenter.sln by local windows debuger
then
WaitJoinGame finished successfully
stdthrow.cpp
line 1760
CommandCenter_d.exe has triggered a breakpoint. occurred

Unhandled exception at 0x00007FF7FC27DCBC in CommandCenter_d.exe: An invalid parameter was passed to a function that considers invalid parameters fatal. occurred

if I run CommandCenter.sln by local windows debuger again
then
did not get a join game response
error in returning observation
the main response is of type 12
there is no response/observation message
no error strings in result

**Comment by davechurchill** [comment]
Can you switch to Release mode and see if it works?

**Comment by slimak2** [comment]
yes, when i run it from \commandcenter-master\commandcenter-master\release\CommandCenter
then its working. but how can i make it work the way i could change code? i need it for my thesis 
Thank you for your help.

**Comment by davechurchill** [comment]
Did you change the working directory as in the instructions?

**Comment by slimak2** [comment]
yes i did this part:
it throws unhandled exception same as described in my post above

**Comment by slimak2** [comment]
I also try to run it on linux but i cant even compile it.

when i do steps : 
$ git clone --recursive https://github.com/Blizzard/s2client-api && cd s2client-api
$ git checkout dd10176ab94cc078a2116ec790b63f0a93ac5527 .
$ mkdir build && cd build
$ cmake ../
$ make

then it will throw me error

[ 83%] Built target sc2protocol
Scanning dependencies of target sc2utils
[ 83%] Building CXX object src/CMakeFiles/sc2utils.dir/sc2utils/sc2_arg_parser.cc.o
[ 83%] Building CXX object src/CMakeFiles/sc2utils.dir/sc2utils/sc2_manage_process.cc.o
/mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc: In function âbool sc2::HasExtension(const string&, const string&)â:
/mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc:84:5: error: no matching function for call to âequal(__gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >, std::basic_string<char>::const_iterator, std::basic_string<char>::const_iterator, std::basic_string<char>::const_iterator, sc2::HasExtension(const string&, const string&)::__lambda0)â
     );
     ^
/mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc:84:5: note: candidates are:
In file included from /usr/include/c++/4.8/vector:60:0,
                 from /mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/../include/sc2utils/sc2_manage_process.h:4,
                 from /mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc:1:
/usr/include/c++/4.8/bits/stl_algobase.h:1021:5: note: template<class _II1, class _II2> bool std::equal(_II1, _II1, _II2)
     equal(_II1 __first1, _II1 __last1, _II2 __first2)
     ^
/usr/include/c++/4.8/bits/stl_algobase.h:1021:5: note:   template argument deduction/substitution failed:
/mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc:84:5: note:   candidate expects 3 arguments, 5 provided
     );
     ^
In file included from /usr/include/c++/4.8/vector:60:0,
                 from /mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/../include/sc2utils/sc2_manage_process.h:4,
                 from /mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc:1:
/usr/include/c++/4.8/bits/stl_algobase.h:1053:5: note: template<class _IIter1, class _IIter2, class _BinaryPredicate> bool std::equal(_IIter1, _IIter1, _IIter2, _BinaryPredicate)
     equal(_IIter1 __first1, _IIter1 __last1,
     ^
/usr/include/c++/4.8/bits/stl_algobase.h:1053:5: note:   template argument deduction/substitution failed:
/mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc:84:5: note:   candidate expects 4 arguments, 5 provided
     );
     ^
make[2]: *** [src/CMakeFiles/sc2utils.dir/sc2utils/sc2_manage_process.cc.o] Error 1
make[1]: *** [src/CMakeFiles/sc2utils.dir/all] Error 2
make: *** [all] Error 2

**Comment by slimak2** [comment]
It would be great if i could make it work on at least one platform. On windows i got most far.

**Comment by slimak2** [comment]
I finally solved it. For anyone who will have the same problem: i used "sc2api_precompiled" as prcompiled libraries but i should have used "SC2API_Binary_vs2017" . I have no idea what is the difference, but its working.
