### ISSUE TITLE
Error on Linux during make

### ISSUE THREAD

**Issue by slimak2** [davechurchill/commandcenter#46]
I am trying to run command center on Linux but it trows me an error during make.

when i do steps :
$ git clone --recursive https://github.com/Blizzard/s2client-api && cd s2client-api
$ git checkout dd10176ab94cc078a2116ec790b63f0a93ac5527 .
$ mkdir build && cd build
$ cmake ../
$ make

then it will throw me error

[ 83%] Built target sc2protocol
Scanning dependencies of target sc2utils
[ 83%] Building CXX object src/CMakeFiles/sc2utils.dir/sc2utils/sc2_arg_parser.cc.o
[ 83%] Building CXX object src/CMakeFiles/sc2utils.dir/sc2utils/sc2_manage_process.cc.o
/mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc: In function âbool sc2::HasExtension(const string&, const string&)â:
/mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc:84:5: error: no matching function for call to âequal(__gnu_cxx::__normal_iterator<const char*, std::basic_string >, std::basic_string::const_iterator, std::basic_string::const_iterator, std::basic_string::const_iterator, sc2::HasExtension(const string&, const string&)::__lambda0)â
);
^
/mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc:84:5: note: candidates are:
In file included from /usr/include/c++/4.8/vector:60:0,
from /mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/../include/sc2utils/sc2_manage_process.h:4,
from /mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc:1:
/usr/include/c++/4.8/bits/stl_algobase.h:1021:5: note: template<class _II1, class _II2> bool std::equal(_II1, _II1, _II2)
equal(_II1 __first1, _II1 __last1, _II2 __first2)
^
/usr/include/c++/4.8/bits/stl_algobase.h:1021:5: note: template argument deduction/substitution failed:
/mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc:84:5: note: candidate expects 3 arguments, 5 provided
);
^
In file included from /usr/include/c++/4.8/vector:60:0,
from /mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/../include/sc2utils/sc2_manage_process.h:4,
from /mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc:1:
/usr/include/c++/4.8/bits/stl_algobase.h:1053:5: note: template<class _IIter1, class _IIter2, class _BinaryPredicate> bool std::equal(_IIter1, _IIter1, _IIter2, _BinaryPredicate)
equal(_IIter1 __first1, _IIter1 __last1,
^
/usr/include/c++/4.8/bits/stl_algobase.h:1053:5: note: template argument deduction/substitution failed:
/mnt/minerva1/nlp/projects/ai_in_games19/s2client-api/src/sc2utils/sc2_manage_process.cc:84:5: note: candidate expects 4 arguments, 5 provided
);
^
make[2]: *** [src/CMakeFiles/sc2utils.dir/sc2utils/sc2_manage_process.cc.o] Error 1
make[1]: *** [src/CMakeFiles/sc2utils.dir/all] Error 2
make: *** [all] Error 2

**Comment by pimmen89** [comment]
I wouldn't recommend checking out that version of the API, it has recently switched out tags to unit pointers.

However, you should be able to make the API. This is an issue with the sc2client-api though, and not with CommandCenter as far as I'm concerned.
