### ISSUE TITLE
How to get the outcome of a match?

### ISSUE THREAD

**Issue by yt4766269** [davechurchill/commandcenter#48]
I am developing a StarCraft2 Ladder platform based on the commandcenter, which lets bots play automatically. However, I cannot find the api of getting the match result. How can I get the outcome of a match?
Thanks.

**Comment by davechurchill** [comment]
You may want to ask this over at the SC2API github, as it is not CC specific

https://github.com/Blizzard/s2client-api

**Comment by KevinCalderone** [comment]
@yt4766269 It is in the underlying protocol, but it looks like we forgot to expose it in the C++ interface. Please add an issue to the repo Dave linked.
