### ISSUE TITLE
ubuntu build fail

### ISSUE THREAD

**Issue by yt4766269** [davechurchill/commandcenter#49]
I tried to build commandcenter in ubuntu16.04 following the steps provided in the readme, However, after I run the make command, countless errors occurred:
Here I list one of them:
/opt/local/lib/sc2api/libsc2protocol.a(data.pb.cc.o):(.rodata._ZTVN14SC2APIProtocol11AbilityDataE[_ZTVN14SC2APIProtocol11AbilityDataE]+0xb0): undefined reference to `google::protobuf::Message::SpaceUsed() const'

How can I solve that? Should I install the specific version of protobuf and rebuild the sc2api?
My cmake version:3.5.1
My g++ version: 5.4.0
My operation system (ubuntu) is newly installed.

**Comment by jhor296** [comment]
I have the same problem, but in Ubuntu 17.10:

g++ version: 7.2
cmake version: 3.9

**Comment by davechurchill** [comment]
closing this for now, as updates to the build file were  just made

**Comment by yt4766269** [comment]
I checked out the old version of sc2 api as the readme said. However, countless errors occurred. They are just same as the issue I have submitted 4 days before.

**Comment by alkurbatov** [comment]
Anyway this issue is dup of #47 but we have no solution so far.

**Comment by alkurbatov** [comment]
The issue was fixed in #52
