### ISSUE TITLE
Can not morph hatchery to lair

### ISSUE THREAD

**Issue by redrabit** [davechurchill/commandcenter#53]
Now I try to morph hatchery to lair. But, It dosen't work properly.
I also insert the word "Lair" in "BotConfig.txt"file, the program always skip this build.
I don't know why this program skip morph lair.
Also I already check conditions for morph lair(builting sporning pool, 150 minerals and 100 gas).
How can I made hatchery morph to lair??
Can you give me any hint to solve this problem??

**Comment by davechurchill** [comment]
Lairs are a special case of creating a building from another building and I probably didn't test it properly. Once I get back from Blizzcon early next week I should be able to fix this quickly.

**Comment by davechurchill** [comment]
So I just checked, and no morphed buildings are currently supported in the bot. This was introduced when I added the BWAPI functionality in the bot, and I just haven't had time to add it in yet. This will be an easy fix, I just need to do it when I get home early next week. Hope you can wait until then :)

**Comment by davechurchill** [comment]
Fixed
