### ISSUE TITLE
Please finish getNextExpansion()

### ISSUE THREAD

**Issue by stolencatkarma** [davechurchill/commandcenter#60]
// TODO: fix this so we can actually expand
 //return m_bot.Bases().getNextExpansion(Players::Self);

in BuildingManager.cpp

note: i've been banging my head against the wall trying to figure out where a valid location for the next hatchery, etc...

maybe someone else can figure this out so i can go back to combat coding. =] thanks.

**Comment by davechurchill** [comment]
Will add this to the top of my list, thanks

**Comment by stolencatkarma** [comment]
going through the Sc2-api it looks like one of the examples already has a way of doing this. in sc2_search.cc is has 
std::vector<Point3D> CalculateExpansionLocations

in the intermediate bot example. hope it helps. =]

**Comment by davechurchill** [comment]
It works now for the first expansion, but there may be bugs with expansions beyond the first (at least in BW). Test it out and report back
