### ISSUE TITLE
Wrong resource location calculation

### ISSUE THREAD

**Issue by luka-papez** [davechurchill/commandcenter#61]
This pull request is similar in nature to this one:
https://github.com/davechurchill/commandcenter/issues/60

The problem is that the calculated resource locations are a bit off, so it causes problems with expansion (i.e. it can't build new geysers). 

The calculations for starting player bases seem to be correct however.
A picture paints a thousand words.

https://imgur.com/a/0rOxk

**Comment by davechurchill** [comment]
This is just parallax error because of the 3D nature of the game - the positions are being drawn much higher than the resources, but they are being calculated accurately. The refinery issue is a separate one

**Comment by luka-papez** [comment]
@davechurchill Are you sure that the positions are calculated correctly? I doubt that's the case, since the images I uploaded clearly show that for some bases the positions are drawn correctly, while for others they are completely off.  In the case of Bel'Shir Vestige map, the two starting bases are drawn correctly, but the error increases for each other base the more distant it is from the starting two.

**Comment by davechurchill** [comment]
Use the mouse wheel to change the viewpoint and you may see what I mean. The 'calculation' of where the resources are is literally just pulling the point from the unit, so there's no way to 'do it wrong'. What you are seeing is me drawing all of the spheres at the same height: that of the maximum height of any unit on the map. That happens to be the level of the starting bases, but not the other bases. I can assure you that it is impossible that those locations are wrong, unless the api itself is wrong.
