### ISSUE TITLE
A situation about  Multiplayer and   Addon

### ISSUE THREAD

**Issue by DotaIsMind** [davechurchill/commandcenter#62]
Hello! I am a newbie who has just used Github and Commander Center,my bot race is Terran,then i want to use  the "CreateParticipant()"   to add the custom bot to i fight with  my bot,
CreateParticipant(Util::GetRaceFromString(botRaceString), &Player),
		CreateParticipant(Util::GetRaceFromString(botRaceString), &bot)
i can open two windows,but the 
else if (item.type.getUnitTypeID() == sc2::UNIT_TYPEID::TERRAN_STARPORTREACTOR)   
			Micro::SmartAddon(producer, sc2::ABILITY_ID::BUILD_REACTOR_STARPORT, m_bot);
is invalid in the game.Do other people have encountered such a problem?

**Comment by DotaIsMind** [comment]
Adding another point,I did not use the latest CommanderCenter.

**Comment by alkurbatov** [comment]
Hi, @DotaIsMind 
I believe the bot can't build Terran addons. See #2

**Comment by davechurchill** [comment]
Yeah the bot can't build addons yet. This is in another issue
