### ISSUE TITLE
Bot always go scout as game starts

### ISSUE THREAD

**Issue by SuminHan** [davechurchill/commandcenter#66]
I don't know how to change this option.

Clearly, the BotConfig.txt:
`"ScoutCondition"    : [ ["Self", "Pylon"], ">", [ 0 ] ],`
but probe always go scout as the game starts.

**Comment by davechurchill** [comment]
Are you sure you are setting it for the correct game?

**Comment by SuminHan** [comment]
Sorry, I think something was wrong. Now it's working.
And i have another problem, how can I build terran refinery?
`
			"Terran_SixMin"     : 
            { 
                "Race"              : "Terran",  
                "OpeningBuildOrder" : ["SCV", "SCV", "SCV", "SCV", "SCV", "Supply Depot", "SCV", "SCV", "Barracks", "SCV", "Refinery", "SCV", "SCV", "SCV", "Supply Depot", "SCV", "SCV", "Factory", "SCV", "Marine", "SCV", "Marine", "SCV", "Marine", "Supply Depot", "Machine Shop", "SCV", "Marine", "SCV", "Marine", "Siege_Tank_Tank_Mode", "Supply Depot", "SCV", "Marine", "Siege_Tank_Tank_Mode", "SCV", "Marine", "Siege_Tank_Tank_Mode"], 
                "ScoutCondition"    : [ ["Self", "SCV"], ">", [ 12 ] ],
                "AttackCondition"   : [ ["Self", "Siege_Tank_Tank_Mode"], ">=", [ 3 ] ]
            },`
This is my Strategy.

**Comment by SuminHan** [comment]
I think I may refer to your ualbertbot's configuration txt file :) I'll try first.
