### ISSUE TITLE
Linker errors after merging latest changes

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [davechurchill/commandcenter#69]
Hi,

I've been using your project for my undergraduate projects and I am not able to run the bot anymore after merging your latest changes. I am now getting the warning
```LNK4098	defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library```
followed by 80 linker errors (LNK2001) all related to the new class UnitType.
And when I try to add this flag, I get over 3000 errors.
The runtime library setting in ```Project Properties -> C/C++ -> Code Generation -> Runtime Library``` is set to Multi-threaded Debug (/MTd) for my debug settings (Debug|x64). I tried the other values with no success.

Do you have an idea of what I need to do?

Thank you,
Raphaël Royer-Rivard

**Comment by davechurchill** [comment]
That is just a warning, it doesn't actually do anything. The last changes were months ago, so it should still be working. Try re-checking it out

**Comment by RaphaelRoyerRivard** [comment]
I know that your last changes were note made recently, but I waited a long time before merging your new code to my fork.
But ok, maybe the warning does not point to the root of my linker errors. They seem to be related to the fact that the compiler cannot find the definitions of the methods listed in the UnitType class header (I cannot find them neither).
![linker_errors](https://user-images.githubusercontent.com/5833235/35129413-81ccd1a2-fc89-11e7-8660-1a8cc5ac04b2.png)

**Comment by davechurchill** [comment]
This error means that the project can't see this function defined in the C++ file.

**Comment by davechurchill** [comment]
I just pulled the project fresh and compiled it no problems. If you have other changes in the code, I cannot know if something you did made this error. It essentially means the linker can't find that function compiled in a linked object file, so most probably the UnitType.cpp file was not compiled into an object file, or not linked correctly. Did you accidentally remove it from the project?

**Comment by alkurbatov** [comment]
Hi @RaphaelRoyerRivard 
Please try to clean up the project and rebuild. Probably some object files were not recompiled after you had applied the latest version.

**Comment by RaphaelRoyerRivard** [comment]
You were both right, I missed the file in my conflict resolution and when I added it back later, it did not compile for whatever reason. I had to remove the file and add it back to the project to make it work.

Thanks to both of you, it is really appreciated.
