### ISSUE TITLE
Run example of Commandcenter,* homeBase = getPlayerStartingBaseLocation(player) is NULL

### ISSUE THREAD

**Issue by Timkeeper2018** [davechurchill/commandcenter#94]
When I try to run CommandcenterDefinitely with VS, I get a null pointer error. This error appears in the 308th sentence in the BaseLocationManager.cpp file:
"Const BaseLocation * homeBase = getPlayerStartingBaseLocation(player);"
My code is not very good, and I can't figure out why the "homeBase" here is a null pointer.
I have installed the required SC2API environment and can successfully run the sample programs in SC2API.
Thanks in advance.

**Comment by davechurchill** [comment]
CommandCenter is no longer being maintained and I'm not even sure the last time it worked properly :(

**Comment by alkurbatov** [comment]
Hi @Timkeeper2018 
Please try on this version
https://github.com/cpp-sc2/commandcenter
